# This is the services.yaml file for the genesisenergy integration.
# It should be placed in: <config_dir>/custom_components/genesisenergy/services.yaml

add_powershout_booking:
  name: Add Power Shout Booking
  description: "Books a Genesis Energy Power Shout for your electricity account."
  fields:
    start_datetime:
      name: Start Datetime
      description: "The date and time (in your Home Assistant's local timezone) for the Power Shout to begin."
      required: true
      example: "2025-06-15 18:00:00"
      selector:
        datetime: {}
    duration_hours:
      name: Duration
      description: "The duration of the Power Shout in hours (e.g., 1, 2, 3, or 4)."
      required: true
      example: 1
      selector:
        number:
          min: 1
          max: 4 # Adjust if API allows more, Genesis typically allows 1-4 hours for standard PS
          step: 1
          mode: slider # or box
          unit_of_measurement: "hr"